# BoW, TF-IDF, ML Algorithms

1. Data Preprocessing & Cleaning
2. Train Test Split
3. BOW and TF-IDF (Sentences -> vectors) - To prevent data leakages
4. Trained The Models

In [698]:
import pandas as pd

In [699]:
messages = pd.read_csv('SMSSpamCollection.txt', sep='\t', names=['label', 'message'])

In [700]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

## Data Cleaning and Preprocessing

In [701]:
import re
import nltk

In [702]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/greatdaveo/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [703]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

In [704]:
ps = PorterStemmer()

In [705]:
corpus = []

for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    
    corpus.append(review)

In [706]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

## For Train Test Split

In [707]:
# Dependent (Output) Features
y = pd.get_dummies(messages['label'])

In [708]:
y

ham   spam
0      True  False
1      True  False
2     False   True
3      True  False
4      True  False
...     ...    ...
5567  False   True
5568   True  False
5569   True  False
5570   True  False
5571   True  False

[5572 rows x 2 columns]

In [709]:
y = y.iloc[:, 0].values

In [710]:
y.shape

(5572,)

In [711]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [712]:
# To do Train Test Split
from sklearn.model_selection import train_test_split

In [713]:
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

## To Create Bag Of Words

In [714]:
# To create the BoWs Model
from sklearn.feature_extraction.text import CountVectorizer

In [715]:
# For Binary BoW enable binary = True
cv = CountVectorizer(max_features=2500, ngram_range=(1, 2))

In [716]:
X_train

['ga station like block away hous drive right sinc armenia end swann take howard',
 'done sorri hope next space give everyth want rememb furnitur around move lock lock leav key jenn',
 'gonna pick burger way home even move pain kill',
 'goodmorn today late hr back pain',
 'eh ur laptop got stock lei say mon muz come take look c got',
 'yeah think',
 'suppos meet discuss abt trip thought xuhui told afternoon thought go lesson',
 'time fix spell sometim get complet diff word go figur',
 'know mood today',
 'also know lunch menu da know',
 'nice day today love dearli',
 'free rington wait collect simpli text password mix verifi get usher britney fml po box mk h ppw',
 'make girl happi difficult make girl happi u need friend companion lover chef lt gt good listen lt gt organ lt gt good boyfriend lt gt clean lt gt sympathet lt gt athlet lt gt warm lt gt courag lt gt determin lt gt true lt gt depend lt gt intellig lt gt psychologist lt gt pest extermin lt gt psychiatrist lt gt healer lt gt s

In [717]:
len(X_train), len(y_train)

(4457, 4457)

In [718]:
# Independent Features
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [719]:
import numpy as np

In [720]:
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))

In [721]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [722]:
cv.vocabulary_

{'ga': 767,
 'station': 1972,
 'like': 1164,
 'away': 132,
 'hous': 979,
 'drive': 575,
 'right': 1753,
 'sinc': 1885,
 'end': 609,
 'take': 2052,
 'done': 557,
 'sorri': 1935,
 'hope': 967,
 'next': 1428,
 'space': 1943,
 'give': 806,
 'everyth': 649,
 'want': 2334,
 'rememb': 1721,
 'around': 96,
 'move': 1367,
 'leav': 1141,
 'key': 1085,
 'gonna': 837,
 'pick': 1567,
 'way': 2355,
 'home': 962,
 'even': 639,
 'pain': 1530,
 'kill': 1091,
 'way home': 2356,
 'goodmorn': 851,
 'today': 2134,
 'late': 1120,
 'hr': 985,
 'back': 136,
 'goodmorn today': 852,
 'today late': 2137,
 'eh': 601,
 'ur': 2234,
 'laptop': 1113,
 'got': 856,
 'stock': 1979,
 'lei': 1150,
 'say': 1803,
 'mon': 1353,
 'muz': 1396,
 'come': 391,
 'look': 1200,
 'yeah': 2477,
 'think': 2099,
 'suppos': 2029,
 'meet': 1294,
 'discuss': 546,
 'abt': 3,
 'trip': 2178,
 'thought': 2108,
 'xuhui': 2461,
 'told': 2142,
 'afternoon': 32,
 'go': 814,
 'lesson': 1152,
 'time': 2119,
 'fix': 715,
 'spell': 1952,
 'sometim': 1

In [723]:
from sklearn.naive_bayes import MultinomialNB

In [724]:
spam_detect_model = MultinomialNB()

In [725]:
spam_detect_model

MultinomialNB()

In [726]:
spam_detect_model = spam_detect_model.fit(X_train, y_train)

In [727]:
y_pred = spam_detect_model.predict(X_test)

In [728]:
from sklearn.metrics import accuracy_score, classification_report

In [729]:
accuracy_score(y_test, y_pred)

0.9847533632286996

In [730]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.94      0.95      0.95       158
        True       0.99      0.99      0.99       957

    accuracy                           0.98      1115
   macro avg       0.97      0.97      0.97      1115
weighted avg       0.98      0.98      0.98      1115



## To create the TF-IDF Model

### Train Test Split

In [731]:
# To do Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.20)

In [732]:
from sklearn.feature_extraction.text import TfidfVectorizer
tv = TfidfVectorizer(max_features=2500, ngram_range=(1, 2))
X_train = tv.fit_transform(X_train).toarray()
X_test = tv.transform(X_test).toarray()

In [733]:
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [734]:
tv.vocabulary_

{'good': 835,
 'go': 811,
 'oh': 1471,
 'haha': 898,
 'den': 530,
 'went': 2371,
 'today': 2130,
 'gee': 781,
 'nvm': 1458,
 'la': 1089,
 'dun': 585,
 'mind': 1300,
 'goin': 831,
 'jazz': 1048,
 'oso': 1513,
 'open': 1498,
 'cant': 291,
 'catch': 310,
 'ok': 1475,
 'lor': 1194,
 'ok lor': 1478,
 'pic': 1563,
 'straight': 1998,
 'phone': 1557,
 'see': 1812,
 'get': 784,
 'wet': 2373,
 'want': 2318,
 'xx': 2461,
 'text': 2074,
 'txt': 2188,
 'cost': 439,
 'ga': 767,
 'xxx': 2462,
 'im': 1005,
 'sorri': 1933,
 'bout': 206,
 'last': 1100,
 'nite': 1430,
 'ur': 2230,
 'fault': 677,
 'give': 803,
 'think': 2094,
 'im sorri': 1006,
 'last nite': 1102,
 'insid': 1023,
 'offic': 1468,
 'still': 1979,
 'fill': 693,
 'know': 1085,
 'leav': 1127,
 'lt': 1218,
 'gt': 871,
 'lt gt': 1220,
 'sent': 1836,
 'wife': 2384,
 'buy': 236,
 'tell': 2062,
 'relax': 1712,
 'go get': 816,
 'oop': 1497,
 'thk': 2099,
 'haf': 897,
 'check': 334,
 'dun haf': 587,
 'guarante': 882,
 'cash': 304,
 'prize': 1645,
 'c

In [735]:
from sklearn.naive_bayes import MultinomialNB
spam_tfidf_model = MultinomialNB()

In [736]:
from sklearn.naive_bayes import MultinomialNB

In [737]:
spam_tfidf_model = MultinomialNB()

In [738]:
spam_tfidf_model

MultinomialNB()

In [739]:
spam_tfidf_model = spam_tfidf_model.fit(X_train, y_train)

In [740]:
# To predict
y_pred = spam_tfidf_model.predict(X_test)

In [741]:
score = accuracy_score(y_test, y_pred)
print(score)

0.9695067264573991


In [742]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

       False       0.78      1.00      0.88       120
        True       1.00      0.97      0.98       995

    accuracy                           0.97      1115
   macro avg       0.89      0.98      0.93      1115
weighted avg       0.98      0.97      0.97      1115

