### Numpy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of a mathematical functions to operate on these data structures. This lesson covers the basics of Numpy, focusing on arrays and vectorized operations.

In [1]:
!pip install numpy

In [2]:
import numpy as np

# To create arrays using numpy
# To create a 1Dimension array

arr1=np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
# 1D array
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) ## 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2 = np.array([[1, 2, 3, 4, 5]])
arr2.shape

(1, 5)

In [5]:
# 2D array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5 ,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
# Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)
print("Shape: \n", arr.shape) # Output: (2, 3)
print("Number of dimensions: \n", arr.ndim) # Output: 2
print("Size (number of elements): \n", arr.size) # Output: 2 
print("Data type: \n", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes): \n", arr.itemsize) # Output: (may vary based on platform)


Array: 
 [[1 2 3]
 [4 5 6]]
Shape: 
 (2, 3)
Number of dimensions: 
 2
Size (number of elements): 
 6
Data type: 
 int64
Item size (in bytes): 
 8


In [12]:
# Numpy Vectorized Operation

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element Wise Addition
print("Addition: ", arr1 + arr2)

# Element Wise Subtraction
print("Subtraction: ", arr1 - arr2)

# Element Wise Multiplication
print("Multiplication: ", arr1 * arr2)

# Element Wise Division
print("Multiplication: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Multiplication:  [0.1 0.1 0.1 0.1 0.1]


In [17]:
# Universal Function
arr = np.array([2, 3, 4, 5, 6])
# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural Log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
# Array Slicing and Indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [34]:
# Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [35]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [42]:
#  Statistical Concepts - Normalization
# To have a mean of 0 and SD of 1
data = np.array([1,2, 3, 4, 5])
# Calculate the mean and standard deviated
mean = np.mean(data)
print("Mean: ", mean)
# Median 
median = np.median(data)
print("Median: ", median)
# Standard deviation
std_dev = np.std(data)
# Variance 
variance = np.var(data)
print("Variance: ", variance)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

Mean:  3.0
Median:  3.0
Variance:  2.0
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [49]:
# Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data[data > 5]


array([ 6,  7,  8,  9, 10])